### ISSUE TITLE
[Domework] - issue

### ISSUE THREAD

**Issue by pgamerx** [PGamerX-Legacy/issues#1]
**Describe the bug**
The bot doesn't fetch the answers and keep saying -
 `Some unexpected Error occurred. Your unique ID is 754557382708822137. Kindly contact my Developers and provide them with this ID so they can work on fixing the error!`

**To Reproduce**
1. Add the bot to a test server
2. Run `d!homework image` command
3. Send the image available at [This link](https://images-ext-1.discordapp.net/external/cEzvZdYtMlj26YN8x1hyQPdtf_cvc-3fm4Gp8z4rY_Q/%3Fwidth%3D517%26height%3D406/https/media.discordapp.net/attachments/894216377710301314/906482995207233556/fd8a96a1-9354-4c2a-8783-9123ceb5ac3a.png) (After downloading)
4. See The Error

**Expected behavior**
The bot should use the OCR system to get a text from the image and do a google search for the same

**Screenshots**
![image](https://user-images.githubusercontent.com/71639879/140611082-71cc0550-9c96-4d7b-9001-e9fb81405e23.png)

**Comment by MarzaElise** [comment]
its me in the picture OOOOOOOOOOOOOOOOOOOOOOOO

**Comment by unknown123456789149** [comment]
Trying to load the logs, didn't yet work. Maybe as @Peiprjs said we should create our own log system and log to discord.

**Comment by Peiprjs** [comment]
Okay so let's do this. Let's just make a new issue

**Comment by pgamerx** [comment]
#2

**Comment by unknown123456789149** [comment]
i just tried it again, this came out
![image](https://user-images.githubusercontent.com/74462750/140651410-8692adaa-e885-4946-a810-f4b3407eb6e8.png)
i think the image isnt clear enough and it returns this cause of that, but idk why yesterday it emitted an error, tho the derived text is totally wrong

**Comment by pgamerx** [comment]
> i just tried it again, this came out ![image](https://user-images.githubusercontent.com/74462750/140651410-8692adaa-e885-4946-a810-f4b3407eb6e8.png) i think the image isnt clear enough and it returns this cause of that, but idk why yesterday it emitted an error, tho the derived text is totally wrong

Intarasting
