### ISSUE TITLE
README - Labels Information

### ISSUE THREAD

**Issue by pgamerx** [PGamerX-Legacy/issues#10]
## Importance Labels 
`1`: Low, one of the last things to do
`2`: Well we could do this as soon as we have no other stuff
`3`: Medium, maybe we should do this soon
`4`: Okay we have to do this
`5`: High, HOLY SHIT EMERGENCY MEETING THE BOT IS IN DANGER

## Bots Labels
`Muser`: For anything related to Muser
`Black Sheep`: For anything related to Black Sheep
`Domework`: For anything related to Domework

## Information labels
`Enhancement`: For any kind of suggestion/enhancement
`Bug`: For any kind of issue/error

**Comment by Peiprjs** [comment]
I'd put this in the readme and tags descriptions

**Comment by Peiprjs** [comment]
Also, level0 = wontfix

**Comment by pgamerx** [comment]
> Also, level0 = wontfix

Not really needed because wontfix label already exists
