### ISSUE TITLE
[Blacksheep] - Fix RS-API

### ISSUE THREAD

**Issue by Peiprjs** [PGamerX-Legacy/issues#14]
Fix the Random Stuff API

**Comment by pgamerx** [comment]
I

**Comment by Peiprjs** [comment]
I meant like fix it in the bot

**Comment by pgamerx** [comment]
oh

**Comment by pgamerx** [comment]
I have fixed it in [f558733ce7d4809705d7e85d87fad70e8c40f3c6](https://github.com/PGamerX-Legacy/blacksheep/commit/f558733ce7d4809705d7e85d87fad70e8c40f3c6)

**Comment by Peiprjs** [comment]
That looks like a stupidly easy fix

**Comment by pgamerx** [comment]
yes

**Comment by pgamerx** [comment]
But I changed other things too lol, Check last 5 commits, they were all about that
