### ISSUE TITLE
[Blacksheep] - feature

### ISSUE THREAD

**Issue by hisRoyalty** [PGamerX-Legacy/issues#5]
**Is your feature request related to a problem? Please describe.**
No, not a problem. It’s for a better experience.
**Describe the solution you'd like**
When speaking to the chatbot, the chatbot fetches from RSA and then sends and it edits the message. For example
- Hi
- Getting response from RSA
- (edits) Hi, my friend, do you want me to tell you a joke?

**Describe alternatives you've considered**
Instead of showing “getting response from RSA”, you could use startTyping() function which adds typing support to the bot.

**Additional context**
I wouldn’t consider this as a huge change to BlackSheep, however, it can make the AI chatbot, probably realistic and a better experience for users.

**Comment by Peiprjs** [comment]
That is actually a pretty good idea.
I give this an importance rating of 2/5

**Comment by LuckieCrab** [comment]
It has finally been added :) 
Will be released in the next restart!
