### ISSUE TITLE
Better error handling for Muser

### ISSUE THREAD

**Issue by Peiprjs** [PGamerX-Legacy/issues#6]

**Comment by Peiprjs** [comment]
In proggers

**Comment by pgamerx** [comment]
@Peiprjs how do we plan on doing this, I don't think so much can be done in November. 
I am shifting this to "To-Do"

**Comment by Peiprjs** [comment]
It should be fairly simple tho?

**Comment by pgamerx** [comment]
> It should be fairly simple tho?

Open sourcing Black sheep, Domework is also there and that will take time as well :)

**Comment by pgamerx** [comment]
#11
