### ISSUE TITLE
[BDM] - Update

### ISSUE THREAD

**Issue by Peiprjs** [PGamerX-Legacy/issues#9]
**Is your feature request related to a problem? Please describe.**
Yes. It's hard to keep up with the updates

**Describe the solution you'd like**
Shell script and crontab job

**Comment by pgamerx** [comment]
Explain more

**Comment by Peiprjs** [comment]
Done

**Comment by Peiprjs** [comment]
First one runs in 40 mins. I finish my break in 25. But I will be available when the logs drop

**Comment by Peiprjs** [comment]
I am having some slight issues with it

**Comment by Peiprjs** [comment]
Done! Can now be found in private repo Randoms
